# Generated by Django 5.1.2 on 2024-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('rating', models.CharField(max_length=4)),
                ('year', models.IntegerField()),
                ('image', models.URLField()),
                ('big_image', models.URLField()),
                ('description', models.TextField()),
                ('genre', models.JSONField()),
                ('imdbid', models.CharField(max_length=50)),
                ('imdb_link', models.URLField()),
            ],
        ),
    ]
